import { QuizQuestion } from './quiz-question.model';

/** Banco de preguntas (cultura dominicana). La partida toma un subconjunto aleatorio según la dificultad. */
export const QUIZ_QUESTION_BANK: QuizQuestion[] = [
  {
    prompt: '¿Cuál es el baile nacional de RD?',
    options: ['Bachata', 'Merengue', 'Salsa', 'Son'],
    correctIndex: 1,
    fact: 'El merengue fue declarado Patrimonio Cultural de la Humanidad por la UNESCO en 2016.',
  },
  {
    prompt: '¿Cuál es la flor nacional?',
    options: ['Orquídea', 'Rosa de Bayahibe', 'Mariposa', 'Hibisco'],
    correctIndex: 1,
    fact: 'La Rosa de Bayahibe es una flor endémica amenazada, símbolo del este.',
  },
  {
    prompt: '¿En qué siglo se introdujo el café en la colonia española de Santo Domingo?',
    options: ['Siglo XVI', 'Siglo XVIII', 'Siglo XIX', 'Siglo XX'],
    correctIndex: 1,
    fact: 'El café se cultivó en la isla desde el siglo XVIII y marcó la economía cafetalera.',
  },
  {
    prompt: '¿Cómo se llama el ave nacional de RD?',
    options: ['Cigua palmera', 'Flamenco', 'Cotorra', 'Gaviota'],
    correctIndex: 0,
    fact: 'La cigua palmera (Dulus dominicus) es endémica y está protegida.',
  },
  {
    prompt: '¿Qué instrumento de percusión es icono del merengue típico?',
    options: ['Conga', 'Tambora', 'Bongó', 'Timbales'],
    correctIndex: 1,
    fact: 'La tambora y la güira son el par clásico del perico ripiao.',
  },
  {
    prompt: '¿En qué provincia tiene lugar el famoso Carnaval de La Vega?',
    options: ['Santiago', 'La Vega', 'San Cristóbal', 'Espaillat'],
    correctIndex: 1,
    fact: 'El carnaval de La Vega es uno de los más reconocidos del Caribe.',
  },
  {
    prompt: '¿Cuál es el árbol nacional?',
    options: ['Caoba', 'Palma real', 'Pine', 'Ceiba'],
    correctIndex: 1,
    fact: 'La palma real (Roystonea borinquena) adorna el escudo nacional.',
  },
  {
    prompt: '¿Qué plato criollo lleva varias carnes, tubérculos y plátanos?',
    options: ['Mangú', 'Sancocho', 'Mofongo', 'Yaroa'],
    correctIndex: 1,
    fact: 'El sancocho dominicano es símbolo de encuentro familiar.',
  },
  {
    prompt: '¿Cómo se llama el himno nacional?',
    options: ['La Bayamesa', 'Quisqueyanos valientes', 'La borinqueña', 'Salve, Oh Patria'],
    correctIndex: 1,
    fact: '“Quisqueyanos valientes” fue compuesto por Emilio Prud’Homme con música de José Reyes.',
  },
  {
    prompt: '¿Cuál es la capital de República Dominicana?',
    options: ['Santiago', 'Santo Domingo', 'La Vega', 'Puerto Plata'],
    correctIndex: 1,
    fact: 'Santo Domingo fue la primera ciudad europea fundada en América (1496–1498).',
  },
  {
    prompt: '¿Cuántos años duró la dictadura de Trujillo (1930–1961) aproximadamente?',
    options: ['21 años', '31 años', '10 años', '40 años'],
    correctIndex: 1,
    fact: 'Rafael Trujillo gobernó de forma autoritaria hasta su asesinato en 1961.',
  },
  {
    prompt: '¿Qué río es el más largo del país?',
    options: ['Yaque del Norte', 'Yaque del Sur', 'Artibonito', 'Ozama'],
    correctIndex: 0,
    fact: 'El Yaque del Norte y su cuenca son clave para agricultura y energía.',
  },
  {
    prompt: '¿Cuál es el pico más alto del Caribe?',
    options: ['Loma Isabel de Torres', 'Pico Duarte', 'Pico Turquino', 'Blue Mountain'],
    correctIndex: 1,
    fact: 'El Pico Duarte supera los 3 000 m y está en la Sierra de Bahoruco/Cordillera Central.',
  },
  {
    prompt: '¿Cuál es la moneda oficial de RD?',
    options: ['Dólar', 'Peso dominicano', 'Peso cubano', 'Euro'],
    correctIndex: 1,
    fact: 'El peso dominicano (RD$) es la moneda de curso legal.',
  },
  {
    prompt: '¿Qué playa famosa está en Pedernales y es conocida por su arena clara?',
    options: ['Bahía de las Águilas', 'Bávaro', 'Cayo Levantado', 'Playa Grande'],
    correctIndex: 0,
    fact: 'Bahía de las Águilas es un paraje protegido del suroeste.',
  },
  {
    prompt: '¿Qué ciudad es conocida como “La cuna del merengue”?',
    options: ['Puerto Plata', 'Santiago', 'Baní', 'San Pedro de Macorís'],
    correctIndex: 1,
    fact: 'Santiago y la región del Cibao son corazón del merengue típico.',
  },
  {
    prompt: '¿Cómo se llama el género rápido de merengue con acordeón, güira y tambora?',
    options: ['Bachata', 'Perico ripiao', 'Son', 'Gagá'],
    correctIndex: 1,
    fact: 'El perico ripiao es una variante rural y festiva del merengue.',
  },
  {
    prompt: '¿Qué día se celebra la Independencia Nacional?',
    options: ['27 de febrero', '16 de agosto', '1 de enero', '12 de octubre'],
    correctIndex: 0,
    fact: 'El 27 de febrero de 1844 marca la independencia respecto a Haití.',
  },
  {
    prompt: '¿Cuál es el apodo popular de Santo Domingo?',
    options: ['La novia del Atlántico', 'La capital de la salsa', 'Ciudad Corazón', 'La perla del Sur'],
    correctIndex: 0,
    fact: '“La novia del Atlántico” es un apodo cariñoso a la capital.',
  },
  {
    prompt: '¿Qué bebida de maíz fermentado tiene raíces taínas y africanas?',
    options: ['Mabi', 'Guarapo', 'Jengibre', 'Malta'],
    correctIndex: 0,
    fact: 'El mabi se elabora con corteza de bejuco u otras recetas criollas.',
  },
  {
    prompt: '¿En qué año Duarte regresó del exilio para la gesta independentista?',
    options: ['1843', '1844', '1865', '1821'],
    correctIndex: 0,
    fact: 'Juan Pablo Duarte es padre de la patria y figura central de la Trinitaria.',
  },
  {
    prompt: '¿Cómo se llama el monumento a los héroes en Santiago?',
    options: ['Faro a Colón', 'Monumento a los Héroes de la Restauración', 'Alcázar de Colón', 'Malecón'],
    correctIndex: 1,
    fact: 'El monumento santiagués honra la Guerra de la Restauración (1863–1865).',
  },
  {
    prompt: '¿Qué provincia alberga Punta Cana, polo turístico mundial?',
    options: ['La Altagracia', 'La Romana', 'Samaná', 'Monte Cristi'],
    correctIndex: 0,
    fact: 'La Altagracia concentra importantes resorts en la costa este.',
  },
  {
    prompt: '¿Cuál es el gentilicio de República Dominicana?',
    options: ['Dominicano', 'Quisqueyano', 'Ambos son usados', 'Antillano'],
    correctIndex: 2,
    fact: '“Dominicano/a” es oficial; “quisqueyano/a” remite a Quisqueya (madre de todas las tierras).',
  },
  {
    prompt: '¿Qué poetisa y educadora dominicana impulsó la educación de las mujeres en el siglo XIX?',
    options: ['Salomé Ureña', 'Pedro Mir', 'Juan Bosch', 'Manuel de Jesús Galván'],
    correctIndex: 0,
    fact: 'Salomé Ureña (1850–1897) es símbolo de letras y pedagogía en RD.',
  },
  {
    prompt: '¿Cuál es la laguna salada más famosa del suroeste?',
    options: ['Lago Enriquillo', 'Presa de Valdesia', 'Lago Hatillo', 'Lima'],
    correctIndex: 0,
    fact: 'El Lago Enriquillo es hipersalino y alberga caimanes y aves únicas.',
  },
  {
    prompt: '¿Qué deporte es el más popular en RD?',
    options: ['Baloncesto', 'Béisbol', 'Fútbol', 'Voleibol'],
    correctIndex: 1,
    fact: 'El béisbol es pasión nacional y exporta grandes ligas.',
  },
  {
    prompt: '¿Cómo se llama el trío de fundadores simbólicos de la independencia?',
    options: ['La Trinitaria', 'Los Padres', 'La Tercera', 'El Triunvirato'],
    correctIndex: 0,
    fact: 'La Trinitaria impulsó la conspiración independista.',
  },
  {
    prompt: '¿Qué ciudad es conocida por su producción de ámbar fósil?',
    options: ['Puerto Plata', 'Santiago', 'Baní', 'San Pedro'],
    correctIndex: 0,
    fact: 'La costa norte, especialmente Puerto Plata, es famosa por el ámbar dominicano.',
  },
  {
    prompt: '¿Cuál es el nombre del río que separa RD de Haití en parte del norte?',
    options: ['Dajabón', 'Masacre', 'Artibonito', 'Yaque del Sur'],
    correctIndex: 0,
    fact: 'El río Dajabón (Masacre) marca tramos de la frontera noroeste.',
  },
  {
    prompt: '¿Qué festividad religiosa mezcla fe católica y cultura afro en Villa Mella?',
    options: ['Gagá', 'Los congos', 'San Juan', 'Carnaval de Bonao'],
    correctIndex: 0,
    fact: 'El gagá y manifestaciones culturales afro son patrimonio vivo en varias regiones.',
  },
  {
    prompt: '¿En qué siglo llegó la colonización española permanente a la isla?',
    options: ['Siglo XV', 'Siglo XVI', 'Siglo XVIII', 'Siglo XIX'],
    correctIndex: 0,
    fact: 'La llegada de Colón en 1492 abrió la colonización europea.',
  },
  {
    prompt: '¿Cómo se llama el plato de plátano majado con huevo y salami típico del desayuno?',
    options: ['Mangú', 'Mofongo', 'Tostones', 'Yuca al mojo'],
    correctIndex: 0,
    fact: 'El mangú con los “tres golpes” es un clásico dominicano.',
  },
  {
    prompt: '¿Qué provincia alberga la Península de Samaná?',
    options: ['Samaná', 'María Trinidad Sánchez', 'Duarte', 'Hato Mayor'],
    correctIndex: 0,
    fact: 'Samaná es famosa por ballenas jorobadas y playas vírgenes.',
  },
  {
    prompt: '¿Cuál es el lema del escudo nacional?',
    options: ['Dios, Patria, Libertad', 'Libertad o muerte', 'Unión y fuerza', 'Patria y vida'],
    correctIndex: 0,
    fact: '“Dios, Patria, Libertad” resume los valores del escudo.',
  },
  {
    prompt: '¿Qué cantautor dominicano popularizó “Ojalá que llueva café”?',
    options: ['Juan Luis Guerra', 'Toño Rosario', 'Wilfrido Vargas', 'Johnny Ventura'],
    correctIndex: 0,
    fact: 'Juan Luis Guerra y 4.40 son referentes de la música dominicana mundial.',
  },
  {
    prompt: '¿Cuántas provincias tiene RD (aprox.)?',
    options: ['32', '25', '10', '50'],
    correctIndex: 0,
    fact: 'El país se divide en 31 provincias y el Distrito Nacional.',
  },
  {
    prompt: '¿Qué personaje es el “Padre de la Patria”?',
    options: ['Máximo Gómez', 'Juan Pablo Duarte', 'Buenaventura Báez', 'Ulises Heureaux'],
    correctIndex: 1,
    fact: 'Duarte encabezó la lucha por la independencia de 1844.',
  },
  {
    prompt: '¿Cuál es la segunda ciudad más poblada del país?',
    options: ['La Romana', 'Santiago de los Caballeros', 'San Pedro', 'Higüey'],
    correctIndex: 1,
    fact: 'Santiago es el corazón del Cibao y gran centro urbano.',
  },
  {
    prompt: '¿Qué instrumento de cuerda acompaña tradicionalmente la bachata?',
    options: ['Cuatro', 'Guitarra', 'Arpa', 'Tres'],
    correctIndex: 1,
    fact: 'La bachata evolucionó con guitarra eléctrica y percusión bailable.',
  },
  {
    prompt: '¿Cómo se llama el parque nacional de montaña en Jarabacoa?',
    options: ['Los Haitises', 'José Armando Bermúdez', 'Isla Saona', 'Cotubanamá'],
    correctIndex: 1,
    fact: 'El parque Bermúdez protege bosques de pino y el Pico Duarte.',
  },
  {
    prompt: '¿Qué dulce criollo se hace con leche y azúcar (textura de tablilla)?',
    options: ['Dulce de leche cortada', 'Flan', 'Arroz con leche', 'Habichuelas con dulce'],
    correctIndex: 0,
    fact: 'La leche cortada es un dulce tradicional de mesa.',
  },
  {
    prompt: '¿En qué mes suelen llegar ballenas a la Bahía de Samaná?',
    options: ['Enero–marzo', 'Julio–agosto', 'Mayo–junio', 'Todo el año'],
    correctIndex: 0,
    fact: 'El avistamiento de ballenas jorobadas es un atractivo invernal-primaveral.',
  },
  {
    prompt: '¿Qué significa “Quisqueya” en la tradición taína popular?',
    options: ['Tierra de montañas', 'Madre de todas las tierras', 'Isla del sol', 'Tierra alta'],
    correctIndex: 1,
    fact: 'Se interpreta como “madre de todas las tierras” en la identidad nacional.',
  },
  {
    prompt: '¿Qué ciudad colonial fue Patrimonio de la Humanidad (UNESCO)?',
    options: ['Zona Colonial de Santo Domingo', 'Puerto Plata', 'Santiago', 'Baní'],
    correctIndex: 0,
    fact: 'La Ciudad Colonial es la primera urbe europea continua en América.',
  },
  {
    prompt: '¿Cuál es el nombre del río que cruza Santo Domingo?',
    options: ['Yaque del Norte', 'Ozama', 'Artibonito', 'Camú'],
    correctIndex: 1,
    fact: 'El Ozama desemboca en el mar Caribe junto a la capital.',
  },
  {
    prompt: '¿Qué líder restauró la independencia en 1865 tras la anexión a España?',
    options: ['Gregorio Luperón', 'Buenaventura Báez', 'Pedro Santana', 'Ulises Espaillat'],
    correctIndex: 0,
    fact: 'La Guerra de la Restauración devolvió la soberanía nacional.',
  },
  {
    prompt: '¿Cómo se llama el plato de habichuelas rojas dulces en Semana Santa?',
    options: ['Habichuelas con dulce', 'Habichuelas con azúcar', 'Dulce de frijoles', 'Potaje dulce'],
    correctIndex: 0,
    fact: 'Las habichuelas con dulce son postre típico cuaresmal.',
  },
  {
    prompt: '¿Qué isla cercana es destino turístico con playas de Bávaro?',
    options: ['Saona', 'Tortuga', 'Cuba', 'Puerto Rico'],
    correctIndex: 0,
    fact: 'Isla Saona y la costa de Punta Cana son íconos del Caribe.',
  },
  {
    prompt: '¿Cuál es el nombre del aeropuerto principal de Santo Domingo?',
    options: ['Las Américas', 'José Francisco Peña Gómez', 'Ambos nombres son correctos', 'Cibao'],
    correctIndex: 2,
    fact: 'El aeropuerto internacional suele citarse como Las Américas o Peña Gómez.',
  },
  {
    prompt: '¿Qué poema es considerado obra de Pedro Mir?',
    options: ['Hay un país en el mundo', 'El otoño', 'La tierra prometida', 'La ciudad ausente'],
    correctIndex: 0,
    fact: 'Pedro Mir (1913–2000) es referente de la poesía social dominicana.',
  },
  {
    prompt: '¿Cuál es la bebida refrescante de limón y jengibre muy criolla?',
    options: ['Morir soñando', 'Jengibre', 'Malta Morena', 'Jugo de chinola'],
    correctIndex: 1,
    fact: 'El jengibre casero es típico en fiestas y ventas callejeras.',
  },
  {
    prompt: '¿Qué ciudad es conocida por el Monumento de Santiago?',
    options: ['Santiago', 'Santo Domingo', 'La Vega', 'San Francisco de Macorís'],
    correctIndex: 0,
    fact: 'El monumento santiagués domina el horizonte del Cibao.',
  },
  {
    prompt: '¿Cuál es el nombre del himno escolar compuesto por Emilio Prud’Homme?',
    options: ['Quisqueyanos valientes', 'Canto a la bandera', 'Himno al trabajo', 'Salve patria'],
    correctIndex: 0,
    fact: 'La letra del himno nacional es de Prud’Homme con música de José Reyes.',
  },
  {
    prompt: '¿Qué producto agrícola es histórico en la región del Cibao además del café?',
    options: ['Cacao', 'Té', 'Maíz', 'Trigo'],
    correctIndex: 0,
    fact: 'RD es productor importante de cacao fino de aroma.',
  },
  {
    prompt: '¿Cómo se llama el ritmo de tambores afro-dominicano en la línea noroeste?',
    options: ['Gagá', 'Raboday', 'Son cubano', 'Dembow'],
    correctIndex: 0,
    fact: 'El gagá y manifestaciones afro son parte del patrimonio inmaterial.',
  },
  {
    prompt: '¿Qué año se proclamó la primera Constitución dominicana?',
    options: ['1844', '1865', '1821', '1845'],
    correctIndex: 0,
    fact: 'La Constitución de 1844 sentó bases del Estado nacional.',
  },
  {
    prompt: '¿Qué apodo tiene la ciudad de Constanza por su clima?',
    options: ['Suiza del Caribe', 'Ciudad del sol', 'Perla del Sur', 'Villa del mar'],
    correctIndex: 0,
    fact: 'Constanza, en altura, tiene clima fresco y paisajes montañosos.',
  },
  {
    prompt: '¿Cuál es el nombre del río que desemboca en el malecón de Santo Domingo?',
    options: ['Ozama', 'Isabela', 'Yaque del Sur', 'Nigua'],
    correctIndex: 0,
    fact: 'El Ozama atraviesa la capital antes de llegar al mar.',
  },
  {
    prompt: '¿Qué festividad honra a la Virgen de la Altagracia?',
    options: ['21 de enero', '27 de febrero', '16 de agosto', '8 de diciembre'],
    correctIndex: 0,
    fact: 'El 21 de enero es día de la Altagracia, patrona espiritual del pueblo.',
  },
  {
    prompt: '¿Cuál es el nombre del parque nacional de manglares en la costa noreste?',
    options: ['Los Haitises', 'Jaragua', 'Sierra de Bahoruco', 'Aniana Vargas'],
    correctIndex: 0,
    fact: 'Los Haitises combinan mogotes, cuevas taínas y manglares.',
  },
  {
    prompt: '¿Qué personaje es el “Benemérito de la Patria”?',
    options: ['Juan Pablo Duarte', 'Pedro Santana', 'Ulises Heureaux', 'Gregorio Luperón'],
    correctIndex: 0,
    fact: 'Duarte recibió honores como fundador moral de la nación.',
  },
  {
    prompt: '¿Cuál es la bebida de leche y naranja famosa en RD?',
    options: ['Morir soñando', 'Jugo de chinola', 'Batida de coco', 'Maltín'],
    correctIndex: 0,
    fact: '“Morir soñando” mezcla leche y jugo de naranja en textura cremosa.',
  },
  {
    prompt: '¿Qué ciudad es conocida como “La capital del cacao”?',
    options: ['San Francisco de Macorís', 'Duarte', 'Hato Mayor', 'El Seibo'],
    correctIndex: 0,
    fact: 'El Cibao oriental y Duarte son zonas cacaoteras.',
  },
  {
    prompt: '¿Qué instrumento raspa en el merengue típico?',
    options: ['Güira', 'Maracas', 'Claves', 'Campana'],
    correctIndex: 0,
    fact: 'La güira metálica es sonido distintivo junto a la tambora.',
  },
  {
    prompt: '¿Cuál es el nombre del lago compartido con Haití al sur?',
    options: ['Enriquillo', 'Azuei', 'Tanganyika', 'Cortés'],
    correctIndex: 0,
    fact: 'El Lago Enriquillo es el más grande del Caribe insular.',
  },
  {
    prompt: '¿Qué ciudad alberga la Basílica de Nuestra Señora de la Altagracia?',
    options: ['Higüey', 'Santiago', 'Baní', 'San Juan de la Maguana'],
    correctIndex: 0,
    fact: 'Higüey recibe millones de peregrinos cada enero.',
  },
  {
    prompt: '¿Cómo se llama el trío de colores de la bandera dominicana?',
    options: ['Rojo, azul y blanco', 'Azul, blanco y rojo', 'Azul, rojo y blanco (sin orden)', 'Todas son correctas'],
    correctIndex: 3,
    fact: 'La bandera es roja, azul y blanco con cruz central.',
  },
];
